# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Arvind Chaturvedi
title: Sr. Software Engineer
email: Arvind.Chaturvedi1092@gmail.com
# email_title: Email (Email title override)
phone: +91-7406062351
# phone_title: Phone (Phone title override)
website: https://drive.google.com/file/d/1QDd5TtwWQkv-uGnTf3_Db6YSGArFk1c1/view?usp=sharing
website_title: Download My Resume from here

# Dark Mode (true/false/never)
darkmode: true

# Social links
github_username:  ArvindChaturvedi
linkedin_username: Arvind-Chaturvedi

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/Arvind-Image.png
about_content: | # this will include new lines to allow paragraphs
  Skilled in a wide range of technologies including Pivotal Cloud Foundry, Kubernetes, AWS, vSphere, GCP, Azure, and more. Proven experience in monitoring and alerting with tools like Splunk, AppDynamics, New Relic, Signal FX, Prometheus, Grafana, and Alertmanager. Proficient in scripting languages such as Bash and Python and familiar with CI/CD tools like Concourse, ArgoCD, and Jenkins.
  Designed and implemented a robust, scalable architecture for the AWS EKS-based platform, incorporating best practices for container orchestration, networking, security, and automated provisioning.
  I have successfully managed and mitigated vulnerabilities in legacy systems and has a track record of creating efficient SOPs and KEDB articles for teams. I am fluent in English and Hindi and is seeking opportunities to leverage his skills to take on professional challenges in the software industry.

content:
  - title: Experience
    layout: list
    content:
      - layout: right
        title: GE Digital
        sub_title: Sr. Software Engineer
        caption: 2021-05 - Current
        quote: >
          Cloud Foundry, Kubernetes, AWS, AWS EKS, Terraform, ArgoCD, Jenkins
        description: | # this will include new lines to allow paragraphs
          Configured/Managed PaaS platform(GE's distribution of Cloud foundry and CFCR/KUBO)

          Deployed Bosh director in Development and Production Environment, managed Custom Bosh releases and configurations

          Performed troubleshooting on Installation issues, Foundation issues and Application issues
  
          Created SOPs and KEDB articles for the team for PaaS, Bosh, Concourse, and Prometheus

          Managed and Mitigated vulnerabilities in the legacy PaaS platform

          Spearheaded the initiative to replace the legacy Cloud Foundry platform with an AWS EKS-based platform as a service (PaaS) solution, leading the architectural design and implementation efforts.

          Designed and implemented a robust, scalable architecture for the AWS EKS-based platform, incorporating best practices for container orchestration, networking, security, and automated provisioning using Terraform and Crossplane.

          Established operational procedures, including monitoring, logging, troubleshooting, and CI/CD pipeline automation, to efficiently manage the AWS EKS platform and enhance developer productivity.

          Collaborated closely with development teams to facilitate the adoption of AWS EKS, providing training, guidance, and support on containerization best practices and AWS services.

          Implemented performance tuning strategies and utilized AWS cost management tools to optimize the efficiency, scalability, and cost-effectiveness of containerized workloads running on the AWS EKS platform.

  - title: Experience
    layout: list
    content:
      - layout: right
        title: British Telecom
        sub_title: Software Engineer
        caption: 2019-11 - 2021-05
        quote: >
          Pivotal Cloud Foundry, Kubernetes(TKGI), AWS, Terraform, CloudFormation
        description: | # this will include new lines to allow paragraphs
          Installed, Managed, upgraded Pivotal cloud foundry (V2.1.X, V2.2.X, V2.3.X, V2.4.X, 2.5.x, 2.6.x, 2.7.x, 2.8.x, 2.9.x) and their compatible versions of service tiles, on IaaS layers (AWS), and have managed application delivery on Platform

          Configured/Managed Quotas, Domains, and spaces in PCF

          Deployed Bosh director in Environment managed Bosh releases and Bosh configurations

          Performed troubleshooting on Installation issues, Foundation issues and Application issues

          Performed backup and complete restore of Bosh Deployments using BBR

          Complete analysis of breaking changes, release notes and known issues for newer versions of Ops Manager, PAS(Formerly Known as ERT) & service tiles

          Based on analysis create roadmap and systematic and error proof upgrade process

          Created SOPs and KEDB articles for team for PCF, Bosh, Concourse, and Prometheus

          Performed complete setup of Concourse server from which can target all foundations

          Completely automated process of foundation upgrade with the help of concourse
  - title: Experience
    layout: list    
    content:
      - layout: right
        title: Synchrony Financial Services
        sub_title: AVP, Cloud Platform Engineer
        caption: 2018-10 - 2019-10
        quote: >
          Pivotal Cloud Foundry, Kubernetes(TKGI), AWS, vSphere, Concourse, PKS, Grafana, Prometheus
        description: | # this will include new lines to allow paragraphs
          Configured/Managed Pivotal Cloud Foundry Administrator skills including Installing and day 2 operational capabilities of Pivotal Cloud Foundry foundations on AWS, vSphere IAAS layers, Application Delivery on Platform, deploy BOSH Director, backing up and Restoring Pivotal Cloud Foundry, Upgrading PCF foundations and advance BOSH troubleshooting skills

          Performed Automating upgrade process and various day-to-day tasks using concourse and shell scripting

          Have set up Prometheus, Grafana, Alert manager as Bosh release to monitor foundations

          Creating new Dashboards in Splunk and New-Relic to generate system and app specific alerts for foundation.

          Communicated business concepts and expected functional behavior to developers and other stakeholders

          Resolved issues and recommended actions based on production and compliance reports

          Collaborated with senior management to develop strategic initiatives and long term goals

          Monitored industry trends, keeping current on latest changes
  - title: Experience
    layout: list     
    content:
      - layout: right
        title: Technical Lead
        sub_title: Cognizant Technology Solutions Pvt. Ltd
        caption: 2014-03 - 2018-10
        quote: >
          Pivotal Cloud Foundry, Kubernetes(TKGI), AWS, AWS EKS, Terraform, CloudFormation
        description: | # this will include new lines to allow paragraphs
          Pivotal Cloud Foundry Administrator skills including Installing Pivotal Cloud Foundry foundations on AWS, AZURE, Vsphere IAAS layers, Application Delivery on the Platform, deploy a BOSH Director, backing up and Restoring Pivotal Cloud Foundry, Upgrading PCF foundations and advance BOSH troubleshooting skill.

          Offered input on technical and platform-related strategic planning initiatives

          Organized system operating procedures to strengthen controls

          Designed support structure needed to confirm scalable application rollouts

          Improved systems with addition of new features and infrastructure

          Installed system updates to address vulnerabilities and reduce security issues

          Drove technical initiatives for large enterprise systems to align with long-term business strategies
  - title: Education
    layout: list
    content:
      - layout: top-right
        title: All Saints' College of Technology
        sub_title: Bachelor Of Engineering
        caption: 2009-2013
        quote: >
          Completed Bachelor of Engineering(Electronics and Comms.) from All Saints' College of Technology
        description: | # this will include new lines to allow paragraphs
          I hold a Bachelor of Engineering degree specializing in Electronics and Communication. My academic background reflects a fervent interest in computer science. My passion lies in leveraging technology to innovate and solve complex problems. I am driven to contribute meaningfully to the advancement of the field through diligent work and continuous learning.
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      I am a versatile individual with a profound passion for diverse pursuits. From excelling in snooker and cricket to delving into autobiographies and finance literature, my intellectual curiosity knows no bounds. A skilled vocalist and avid consumer of cinematic narratives, I navigate between melodies and movies with finesse. However, it is my adventurous spirit that truly defines me, as I embark on exhilarating bike journeys, embracing the allure of the open road. I epitomizes a blend of sophistication and adventurous spirit, continually seeking knowledge and exploration, making each endeavor a testament to my dynamic character and unwavering enthusiasm.

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]